---

#
esphome:
  name: rainfalldevice
  friendly_name: rainfall

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
#

# dfrobot_sen0575_i2c
external_components:
  - source: github://foreign-sub/DFRobot-Rainfall-Sensor-SEN0575-i2c

i2c:
  sda: GPIO21
  scl: GPIO22
  frequency: 100kHz
  timeout: 50ms
  id: bus_a

sensor:
  - platform: dfrobot_sen0575_i2c
    i2c_id: bus_a
    # id: rainfall_sensor # optional id
    cumulative_rainfall:
      name: "Cumulative Rainfall"
    rainfall_within_hour:
      name: "Rainfall within hour"
      rainfall_hour: 1 # optional rainfall hour (default to 1)
    raw_data:
      name: "Raw Data"
    working_time:
      name: "Working Time"

# dfrobot_sen0575_i2c
